server: 
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe?ssl=false
    username: solstory
    password: eyessolstory
    #url: jdbc:oracle:thin:@solstory.c1e666eai6lh.us-east-1.rds.amazonaws.com:1521:ORCL
    #username: admin
    #password: eyessolstory12
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true


logging:
  level:
    '[com.zaxxer.hikari]': TRACE
    '[org.springframework.jdbc.datasource]': TRACE
    '[org.hibernate.SQL]': TRACE
    '[org.hibernate.type.descriptor.sql]': TRACE

api:
  key: 'cb6cca464d504a29a809ced072ba5aec'
